# Generated by Django 3.1 on 2024-11-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField()),
                ('diseases', models.JSONField()),
                ('medicines', models.JSONField()),
                ('medical_tests', models.JSONField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
