# Generated by Django 3.1 on 2024-11-09 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_finaldiagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
