# Generated by Django 3.1 on 2024-11-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_finaldiagnosis_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaldiagnosis',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
